#!/usr/bin/env bash

# ONLY FOR DEBIAN 9
# -----------------

# init
while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help|*)
            cat <<EOF
INSTALL TOOL OF OPENBOX WM ON DEBIAN 9

Arguments:
	-h  Showing this help.
EOF
            exit 0
            ;;
    esac
done

# configuration sudo
echo -e ">>> Configuration sudo\n"
apt install -y sudo
read -s -p "Your new primary username: " username
usermod -aG sudo $username
# swithing to new user
sudo - $username
cd

# configuration locales
echo -e ">>> Configuration locales\n"
sudo dpkg-reconfigure locale

# configuration keyboard
echo -e ">>> Configuration keyboard\n"
sudo cp ./etc/default/keyboard /etc/default/keyboard
loadkeys us

# configuration ethernet
echo -e ">>> Configuration Ethernet\n"
read -s -p "Connect to WiFi? (y/n) " connectToWifi
if connectToWifi;
	read -s -p "SSID: " wifiSsid
	read -s -p "Password: " wifiPassword

	sudo cp /etc/interface/interfaces /etc/interface/interfaces.bak
	sudo cat ./etc/network/interfaces | sed "s/@SSID@/${wifiSsid}/" | sed "s/@PSK@/${wifiPassword}/" > /etc/interface/
fi

# installing packages
echo -e ">>> Installing packages\n"
sudo apt install -y xorg openbox tint2 pcmanfm xterm chromium lxappearance git gsimplecal audacious \
	feh geany gparted htop network-manager network-manager-gnome pavucontrol pnmixer obconf \
	pulseaudio resolvconf screenfetch scrot vim vlc xfce4-power-manager zip lxrandr lxinput obmenu

read -s -p "Do you have Realtek Ethernet chipset? (y/n) " isRealtekChipset
if isRealtekChipset;
	sudo apt install -y firmware-realtek
fi
read -s -p "Do you have Atheros Ethernet chipset? (y/n) " isAtherosChipset
if isRealtekChipset;
	sudo apt install -y firmware-atheros
fi
	
# installing icons
echo -e ">>> Installing icons\n"
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/20190331/install.sh | sh

# installing themes
echo -e ">>> Installing themes\n"
cp -R ./.themes ~/

# copying configurations
echo -e ">>> Copying local configurations\n"
cp -R ./.config ~/
cp ./.xinitrc ~/
cp ./.vimrc ~/
cat ./.bash_profile | sed "s/@username@/${username}/" > ~/.bash_profile
cp ./.Xresources ~/

# copying wallpapers
echo -e ">>> Copying wallpapers\n"
cp -R ./Wallpapers ~/

# clearing
sudo mv /etc/interface/interfaces.bak /etc/interface/interfaces

# ending
echo -e "DONE! YOU MUST RESTART YOUR COMPUTER NOW.\n"
