#!/usr/bin/env bash

# ONLY FOR DEBIAN 9
# -----------------

# init
while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help|*)
            cat <<EOF
INSTALL TOOL OF OPENBOX WM ON DEBIAN 9

Arguments:
	-h  Showing this help.
EOF
            exit 0
            ;;
    esac
done

RESOURCE_URL=https://raw.githubusercontent.com/bupy7/my-openbox-wm/master/light

# configuration sudo
apt install -y sudo

read -s -p "Your not root username: " username

usermod -aG sudo $username

# swith to new user
sudo - $username
cd

# configuration locales
sudo dpkg-reconfigure locale

# install packages
sudo apt install -y xorg \
	openbox \
	tint2 \
	pcmanfm \
	xterm \
	chromium \
	lxappearance \
	git \
	gsimplecal
	
# install icons
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/20190331/install.sh | sh
	
# download wallpapers
mkdir ~/wallpapers
wget -O ~/wallpapers/meg-myers-1.jpg ${RESOURCE_URL}/wallpapers/meg-myers-1.jpg

# configuration Xorg
wget -O ~/.xinitrc ${RESOURCE_URL}/.xinitrc
chmod +x ~/.xinitrc

# configuration .bash_profile
wget -O ~/.bash_profile ${RESOURCE_URL}/.bash_profile
chmod +x ~/.bash_profile

# configuration openbox
if [[ ! -d ~/.config/openbox ]]; then
	mkdir -p ~/.config/openbox
fi
wget -O ~/.config/openbox/autostart.sh ${RESOURCE_URL}/.config/openbox/autostart.sh
chmod +x ~/.config/openbox/autostart.sh
wget -O ~/.config/openbox/menu.xml ${RESOURCE_URL}/.config/openbox/menu.xml
wget -O ~/.config/openbox/rc.xml ${RESOURCE_URL}/.config/openbox/rc.xml

# configuration tint2
if [[ ! -d ~/.config/tint2 ]]; then
	mkdir -p ~/.config/tint2
fi
wget -O ~/.config/tint2/tint2rc ${RESOURCE_URL}/.config/tint2/tint2rc
